// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCurH5YDs_ozWjD-F6XWwcDZ7WSps9RSEU',
    appId: '1:892587294289:web:d84a74526677a44dcfc270',
    messagingSenderId: '892587294289',
    projectId: 'expense-tracker-864ef',
    authDomain: 'expense-tracker-864ef.firebaseapp.com',
    storageBucket: 'expense-tracker-864ef.firebasestorage.app',
    measurementId: 'G-4WVE1TVRGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdcR1Ym0tDpKNzZZB3PDfXT0RpiVCelc',
    appId: '1:892587294289:android:63c25a6c900dc0f5cfc270',
    messagingSenderId: '892587294289',
    projectId: 'expense-tracker-864ef',
    storageBucket: 'expense-tracker-864ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDsoQqUz3skbkqzaLt7oG87Od_bIHJCg',
    appId: '1:892587294289:ios:b992f6e9d1e7e19dcfc270',
    messagingSenderId: '892587294289',
    projectId: 'expense-tracker-864ef',
    storageBucket: 'expense-tracker-864ef.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDsoQqUz3skbkqzaLt7oG87Od_bIHJCg',
    appId: '1:892587294289:ios:b992f6e9d1e7e19dcfc270',
    messagingSenderId: '892587294289',
    projectId: 'expense-tracker-864ef',
    storageBucket: 'expense-tracker-864ef.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCurH5YDs_ozWjD-F6XWwcDZ7WSps9RSEU',
    appId: '1:892587294289:web:4244f96af9bb25d7cfc270',
    messagingSenderId: '892587294289',
    projectId: 'expense-tracker-864ef',
    authDomain: 'expense-tracker-864ef.firebaseapp.com',
    storageBucket: 'expense-tracker-864ef.firebasestorage.app',
    measurementId: 'G-HK2JZHKZJG',
  );
}
